package forme;

import javax.swing.JFrame;


public class AdministratorForma extends javax.swing.JFrame {
    UnosDogadjaja unosDogadjajaForma;
    UnosClana unosClanaForma;
    BrisanjeDogadjaja brisanjeDogadjajaForma;
    BrisanjeClanova brisanjeClanaForma;
    AzuriranjeDogadjaja azuriranjeDogadjajaforma;
    PregledClanova pregledClanovaForma;
    UnosDrzave unosDrzaveForma;
    
    /**
     * Creates new form AdminForma
     */
    public AdministratorForma() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setExtendedState(this.MAXIMIZED_BOTH);
        //this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem6 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmUnosDogadjaja = new javax.swing.JMenuItem();
        jmUnosClanova = new javax.swing.JMenuItem();
        jmUnosDrzava = new javax.swing.JMenuItem();
        hmBrisanjeDogadjaja = new javax.swing.JMenuItem();
        jmBrisanjeClanova = new javax.swing.JMenuItem();
        jmAzuriranjeDogadjajima = new javax.swing.JMenuItem();
        jmPregledClanova = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        jCheckBoxMenuItem6.setSelected(true);
        jCheckBoxMenuItem6.setText("jCheckBoxMenuItem6");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator forma");

        jMenu1.setText("Opcije");

        jmUnosDogadjaja.setText("Unos dogadjaja");
        jmUnosDogadjaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUnosDogadjajaActionPerformed(evt);
            }
        });
        jMenu1.add(jmUnosDogadjaja);

        jmUnosClanova.setText("Unos clanova");
        jmUnosClanova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUnosClanovaActionPerformed(evt);
            }
        });
        jMenu1.add(jmUnosClanova);

        jmUnosDrzava.setText("Unos država");
        jmUnosDrzava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUnosDrzavaActionPerformed(evt);
            }
        });
        jMenu1.add(jmUnosDrzava);

        hmBrisanjeDogadjaja.setText("Brisanje dogadjaja");
        hmBrisanjeDogadjaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hmBrisanjeDogadjajaActionPerformed(evt);
            }
        });
        jMenu1.add(hmBrisanjeDogadjaja);

        jmBrisanjeClanova.setText("Brisanje clnaova");
        jmBrisanjeClanova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBrisanjeClanovaActionPerformed(evt);
            }
        });
        jMenu1.add(jmBrisanjeClanova);

        jmAzuriranjeDogadjajima.setText("Ažuriranje podataka o dogadjajima");
        jmAzuriranjeDogadjajima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAzuriranjeDogadjajimaActionPerformed(evt);
            }
        });
        jMenu1.add(jmAzuriranjeDogadjajima);

        jmPregledClanova.setText("Pretraga i pregled clanova");
        jmPregledClanova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPregledClanovaActionPerformed(evt);
            }
        });
        jMenu1.add(jmPregledClanova);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmUnosDogadjajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUnosDogadjajaActionPerformed
        // TODO add your handling code here:
        unosDogadjajaForma = new UnosDogadjaja();
        unosDogadjajaForma.setDefaultCloseOperation(UnosDogadjaja.DISPOSE_ON_CLOSE);
        unosDogadjajaForma.pack();
        unosDogadjajaForma.setVisible(true);
    }//GEN-LAST:event_jmUnosDogadjajaActionPerformed

    private void jmAzuriranjeDogadjajimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAzuriranjeDogadjajimaActionPerformed
        // TODO add your handling code here:
        azuriranjeDogadjajaforma = new AzuriranjeDogadjaja();
        azuriranjeDogadjajaforma.setDefaultCloseOperation(AzuriranjeDogadjaja.DISPOSE_ON_CLOSE);
        azuriranjeDogadjajaforma.pack();
        azuriranjeDogadjajaforma.setVisible(true);
    }//GEN-LAST:event_jmAzuriranjeDogadjajimaActionPerformed

    private void jmUnosClanovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUnosClanovaActionPerformed
        // TODO add your handling code here:
        unosClanaForma = new UnosClana();
        unosClanaForma.setDefaultCloseOperation(UnosClana.DISPOSE_ON_CLOSE);
        unosClanaForma.pack();
        unosClanaForma.setVisible(true);
    }//GEN-LAST:event_jmUnosClanovaActionPerformed

    private void jmUnosDrzavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUnosDrzavaActionPerformed
        // TODO add your handling code here:
        unosDrzaveForma = new UnosDrzave();
        unosDrzaveForma.setDefaultCloseOperation(UnosDrzave.DISPOSE_ON_CLOSE);
        unosDrzaveForma.pack();
        unosDrzaveForma.setVisible(true);
    }//GEN-LAST:event_jmUnosDrzavaActionPerformed

    private void hmBrisanjeDogadjajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hmBrisanjeDogadjajaActionPerformed
        // TODO add your handling code here:
        brisanjeDogadjajaForma = new BrisanjeDogadjaja();
        brisanjeDogadjajaForma.setDefaultCloseOperation(BrisanjeDogadjaja.DISPOSE_ON_CLOSE);
        brisanjeDogadjajaForma.pack();
        brisanjeDogadjajaForma.setVisible(true);
    }//GEN-LAST:event_hmBrisanjeDogadjajaActionPerformed

    private void jmBrisanjeClanovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBrisanjeClanovaActionPerformed
        // TODO add your handling code here:      
        brisanjeClanaForma = new BrisanjeClanova();
        brisanjeClanaForma.setDefaultCloseOperation(BrisanjeClanova.DISPOSE_ON_CLOSE);
        brisanjeClanaForma.pack();
        brisanjeClanaForma.setVisible(true);
    }//GEN-LAST:event_jmBrisanjeClanovaActionPerformed

    private void jmPregledClanovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPregledClanovaActionPerformed
        // TODO add your handling code here:
        pregledClanovaForma = new PregledClanova();
        pregledClanovaForma.setDefaultCloseOperation(PregledClanova.DISPOSE_ON_CLOSE);
        pregledClanovaForma.pack();
        pregledClanovaForma.setVisible(true);
    }//GEN-LAST:event_jmPregledClanovaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministratorForma().setVisible(true);
            }
        });
    }

    public UnosDogadjaja getUnosDogadjajaForma() {
        return unosDogadjajaForma;
    }

    public UnosClana getUnosClanaForma() {
        return unosClanaForma;
    }

    public BrisanjeDogadjaja getBrisanjeDogadjajaForma() {
        return brisanjeDogadjajaForma;
    }

    public BrisanjeClanova getBrisanjeClanaForma() {
        return brisanjeClanaForma;
    }

    public AzuriranjeDogadjaja getAzuriranjeDogadjajaforma() {
        return azuriranjeDogadjajaforma;
    }

    public PregledClanova getPregledClanovaForma() {
        return pregledClanovaForma;
    }

    public UnosDrzave getUnosDrzaveForma() {
        return unosDrzaveForma;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem hmBrisanjeDogadjaja;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jmAzuriranjeDogadjajima;
    private javax.swing.JMenuItem jmBrisanjeClanova;
    private javax.swing.JMenuItem jmPregledClanova;
    private javax.swing.JMenuItem jmUnosClanova;
    private javax.swing.JMenuItem jmUnosDogadjaja;
    private javax.swing.JMenuItem jmUnosDrzava;
    // End of variables declaration//GEN-END:variables
}
